%% surveyAnalysis_POEM_v1_1s
% Analysis code for the Penn Online Evaluation of Migraine (POEM)
%
% Description:
%   This routine loads the .csv files generated by Qualtrics that have the
%   results of the migraine diagnostic pathway. The link the data for the
%   Aguirre lab can be found here:
%
%       https://upenn.co1.qualtrics.com/jfe/form/SV_4NQzKbssiT8qqVf
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all

%% Set paths to data and output
projectDir=getpref('surveyMelanopsinAnalysis', 'projectDir');
sourceDir = '~/Desktop/POEM_v1.1s_Analysis/';
outputDir = '~/Desktop/POEM_v1.1s_Analysis/';

% If the output directory does not exist, create it
if ~exist(outputDir,'dir')
    mkdir(outputDir)
end

% Set filenames
qualtricsDataFile = fullfile(sourceDir,'POEM_v1.1s_March 12, 2018_15.49.csv');
outputResultExcelName=fullfile(outputDir,'POEM_v1.1s_results.xlsx');


%% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = poemAnalysis_preProcess(qualtricsDataFile);


%% classify headache based upon table T
diagnosisTable = poemAnalysis_classify( T );
writetable(diagnosisTable,outputResultExcelName,'Range','A4','WriteRowNames',true)


